sample_app1/config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :buyers
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

sample_app1/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

sample_app1/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app1/app/views/static_pages/User.html.erb
<h1>StaticPages#User</h1>
<p>Find me in app/views/static_pages/User.html.erb</p>

sample_app1/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Se enfocan principalmente en negocios y restaurantes, con posibilidad de ir a casas, pero todos los productos que ofrecen 
  son principalmente con plagas que se ven en edificios no tanto en residencias.
  Ofrecen servicio de exterminacion, pero su enfoque principal es el vender productos de 
  calidad que permitan aniquilar plagas sin verse en la necesidad de ocupar un dia o un fin de semana completo,
  y asi evitar que el negocio tenga que suspender sus operaciones.
</p>
<p>
  La mision de la empresa es poder atender la creciente demanda de exterminio de plagas de roedores que se desarrolla en la zona 
  sur de la ciudad y zona de restaurantes del centro.
</p>
<p>
  Su vision, es poder proveer un servicio de calidad de manera que puedan ser una fuente confiable de servicio de exterminacion 
  de plagas, y ofrecer productos de calidad que permitan que los clientes solo tengan que usarlos una vez, pero recomendarlos asi mismo mas de una.
</p>

sample_app1/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contacto: Andres Anaya Esteinou
</p>
<p>
  Nombre de la empresa: CIP Express(Control Integrado de Plagas)
</p>
<p>
  Descripcion: Control de plagas
</p>
<p>
  Especializan en roedores pero hacen todo tipo de exterminacion de eplagas: cucarachas, 
  langostas(las que matan cultivos), gatos, en ocasiones perros callejeros temritas, y polillas.
</p>
<p>
  Ubicados: Colonia San Rafael Delegacion Cuahutemoc, calle Virginia Fabregas #68
</p>
<p>
  Telefono: 5520109639
</p>

sample_app1/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Ubicados: Colonia San Rafael Delegacion Cuahutemoc, calle Virginia Fabregas #68
</p>
<p>
  Telefono: 5520109639
</p>

sample_app1/app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>
  <div class="center jumbotron">
    <h1>Bienvenido: </h1>
    <h2>
      Esta es tu la pagina principal
      <h3>
        Para empezar a trabajar puedes checar la tabla de ventas en el boton de abajo y asi registrar todo lo que vas haciendo.
        Recuerda que puedes checar en los otros menus los objetos que vendemos y algunos compradores comunes.
      </h3>
    </h2>
    <%= link_to "Tablas", buyers_path, class: "btn btn-lg btn-danger" %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Bienvenido</h1>

    <h2>
      Esta es la pagina principal
      <h3>
        Si eres un usuario ingresa en log in, de lo contrario haz sign up.
      </h3>
    </h2>

    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-danger" %>
  </div>

  <%= link_to image_tag("tec.jpg", alt: "rand image") %>
<% end %>