sample_app1/config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :buyers
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

sample_app1/app/models/buyer.rb
class Buyer < ActiveRecord::Base
    validates :Nombre,  presence: true, length: { maximum: 50 }, uniqueness: true
    validates :Direccion,  presence: true, length: { maximum: 200 }
    validates :Telefono,  presence: true, length: { maximum: 10 }, numericality: { only_integer: true },
    numericality: {greater_than_or_equal_to: 0}
end

sample_app1/app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  
  def create
    @buyer = Buyer.new(buyer_params)
      if @buyer.save
        flash[:success] = "Comprador creado con exito"
        redirect_to @buyer
      else
        render 'new'
      end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        flash[:success] = "Elemento updated"
        format.html { redirect_to @buyer }
      else
        render 'edit'
      end
      
    end
  end
  # DELETE /buyers/1
  # DELETE /buyers/1.json

  def destroy
    @buyer.destroy
    flash[:success] = "Comprador Destruido"
    redirect_to buyers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:Index, :Nombre, :Direccion, :Telefono)
    end
end

sample_app1/app/helpers/buyers_helper.rb
module BuyersHelper
end

sample_app1/app/views/buyers/_form.html.erb
<%= form_for(@buyer) do |f| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% @buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Direccion %><br>
    <%= f.text_field :Direccion %>
  </div>
  <div class="field">
    <%= f.label :Telefono %><br>
    <%= f.text_field :Telefono %>
  </div>
  <div class="actions">
    <%= f.submit "Crear", class: "btn btn-danger" %>
  </div>
<% end %>

sample_app1/app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

sample_app1/app/views/buyers/index.html.erb
<h1>Lista Compradores</h1>
  <div class="container">
  <p>Aqui estan los compradores:</p>                                          
  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr>
        <th>Index</th>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>Telefono</th>
      </tr>
    </thead>
    <tbody>
      <% @buyers.each do |buyer| %>
        <tr>
          <td><%= buyer.id %></td>
          <td><%= buyer.Nombre %></td>
          <td><%= buyer.Direccion %></td>
          <td><%= buyer.Telefono %></td>
          <td><%= link_to 'Show', buyer %></td>
          <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
          <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<%= link_to 'Nuevo Comprador', new_buyer_path, class: "btn btn-danger" %>

sample_app1/app/views/buyers/new.html.erb
<h1>Nuevo Comprador</h1>

<%= render 'form' %>

<%= link_to 'Back', buyers_path %>

sample_app1/app/views/buyers/show.html.erb
<% provide(:title, @buyer.Nombre) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        Comprador <%= @buyer.id %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <p>
      <strong>Nombre:</strong>
      <%= @buyer.Nombre %>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <strong>Direccion:</strong>
      <%= @buyer.Direccion %>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <strong>Telefono:</strong>
      <%= @buyer.Telefono %>
    </p>
  </div>
<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>